# Generated by Django 5.0 on 2025-01-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Модерировано')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Офлайн встреча',
                'verbose_name_plural': 'Офлайн встречи',
                'ordering': ['event_date'],
            },
        ),
    ]
