# Generated by Django 5.0 on 2025-03-13 00:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Офлайн встреча',
                'verbose_name_plural': 'Офлайн встречи',
                'ordering': ['event_date'],
            },
        ),
    ]
