# Generated by Django 5.0 on 2025-01-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineevent',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='offlineevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offlineevent',
            name='is_moderated',
        ),
        migrations.AlterField(
            model_name='offlineevent',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения'),
        ),
    ]
