# Generated by Django 5.0 on 2025-01-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
