# Generated by Django 5.0 on 2025-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_moderated',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='URL статьи будет сгенерирован автоматически', unique=True, verbose_name='URL'),
        ),
    ]
