# Generated by Django 5.0 on 2025-01-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UstazProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('achievements', models.TextField(verbose_name='Достижения')),
            ],
            options={
                'verbose_name': 'Профиль устаза',
                'verbose_name_plural': 'Профиль устаза',
            },
        ),
        migrations.CreateModel(
            name='UstazGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ustaz_gallery/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lessons.ustazprofile')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
