# Generated by Django 5.0 on 2025-01-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lesson_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
