# Generated by Django 5.0 on 2025-01-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', '-is_intro', 'order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order', 'is_intro')},
        ),
    ]
