# Generated by Django 5.0 on 2025-01-16 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_options_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustazprofile',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
