# Generated by Django 5.0 on 2025-04-20 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL для перехода')),
                ('notification_type', models.CharField(choices=[('comment_reply', 'Ответ на комментарий'), ('question_answer', 'Ответ на вопрос'), ('new_comment', 'Новый комментарий к уроку'), ('new_question', 'Новый вопрос'), ('new_lesson', 'Новый урок'), ('new_event', 'Новая оффлайн встреча'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sent_to_browser', models.BooleanField(default=False, verbose_name='Отправлено в браузер')),
                ('sent_to_telegram', models.BooleanField(default=False, verbose_name='Отправлено в Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push-уведомления')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email-уведомления')),
                ('notification_types', models.JSONField(default=dict, verbose_name='Типы уведомлений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField(verbose_name='Информация о подписке')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Браузер')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Устройство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push-подписка',
                'verbose_name_plural': 'Push-подписки',
            },
        ),
    ]
